version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - run:
          name: Install Ruby dependencies
          command: bundle install
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Copy USWDS files and assets
          command: npm run update-uswds
      - run:
          name: Build
          command: JEKYLL_ENV=production bundle exec jekyll build
      - run:
          name: Test
          command: htmlproofer --check-favicon --check-html --disable-external _site
