version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build
          command: JEKYLL_ENV=production bundle exec jekyll build
